#!/bin/sh
# postrm script for adpi-firmware
#
# see: dh_installdeb(1)

set -e

OVERLAY=adpipro
CONFIG=/boot/config.txt

case "$1" in
    purge)
        if [ -e $CONFIG ]; then
            sed $CONFIG -i -e "s@^(device_tree_|dt)overlay=${OVERLAY}.*\n@@"
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0
