#!/bin/sh
# preinst script for adpi-firmware
#
# see: dh_installdeb(1)

set -e

DTBS="adpipro-cs0.dtbo adpipro-cs1.dtbo"
OVERLAY_DIR=/boot/overlays

do_backup() {
    overlay=$1
    if [ -e ${OVERLAY_DIR}/${overlay}.old ]; then
        echo "remove old backup"
        rm ${OVERLAY_DIR}/${overlay}.old
    fi
    if [ -e ${OVERLAY_DIR}/${overlay} ]; then
        echo "backup firmware to ${OVERLAY_DIR}/${overlay}.old"
        mv ${OVERLAY_DIR}/${overlay} ${OVERLAY_DIR}/${overlay}.old
    fi
}

case "$1" in
    install|upgrade)
        for dtb in $DTBS
        do
            do_backup $dtb
        done
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0

